// Generated by Scaffolding ts
// An app developed by Brainglab, Website: https://brainglab.com

import 'dart:convert';

class Countries {
  List<Country> items = [];

  Countries();

  Countries.fromJsonList(List<dynamic>? jsonList) {
    if (jsonList == null) {
      return;
    } else {
      for (var item in jsonList) {
        final mCountry = Country.fromJsonMap(item);
        items.add(mCountry);
      }
    }
  }

  String toArrayJson() {
    String jsonArray = '';
    for (var i = 0; i < items.length; i++) {
      jsonArray += items[i].toJson();

      if ((i + 1) < items.length) {
        jsonArray += ", ";
      }
    }

    return jsonArray = '[$jsonArray]';
  }
}

class Country {
  String? mIdx;
  String? mCountryName;
  String? mCountryCodeLetter;
  String? mCountryCode;
  String? mCountryFlagUrl;
  DateTime? mCreatedAt;
  DateTime? mUpdatedAt;

  Country({
    mIdx,
    mCountryName,
    mCountryCodeLetter,
    mCountryCode,
    mCountryFlagUrl,
    mCreatedAt,
    mUpdatedAt,
  });

  Country.fromJsonMap(Map<String, dynamic> json) {
    mIdx = json['idx'];
    mCountryName = json['country_name'];
    mCountryCodeLetter = json['country_code_letter'];
    mCountryCode = json['country_code'];
    mCountryFlagUrl = json['country_flag_url'];
    mCreatedAt = json['created_at'] == null ? null : DateTime.parse(json['created_at']);
    mUpdatedAt = json['updated_at'] == null ? null : DateTime.parse(json['updated_at']);
  }

  String toJson() {
    return jsonEncode(_toJsonMap());
  }

  Map<String, dynamic> _toJsonMap() => {
        'idx': mIdx,
        'country_name': mCountryName,
        'country_code_letter': mCountryCodeLetter,
        'country_code': mCountryCode,
        'country_flag_url': mCountryFlagUrl,
        'created_at': mCreatedAt,
        'updated_at': mUpdatedAt,
      };
}
